# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

admin = User.create(username:'admin', password: '1', email:'admin@gmail.com', full_name:'joe jackson');

document = Nda.create(user_id: '1', nda:'<p>Increment LTD., and {full_name}, agree:</p><p>Increment LTD. may from time to time disclose to {full_name} certain confidential information or trade secrets generally regarding .</p><p>{full_name} agrees that it shall not disclose the information so conveyed, unless in conformity with this agreement. {full_name} shall limit disclosure to the officers and employees of {full_name} with a reasonable &quot;need to know&quot; the information, and shall protect the same from disclosure with reasonable diligence.</p><p>As to all information which Increment LTD. claims is confidential, Increment LTD. shall reduce the same to writing prior to disclosure and shall conspicuously mark the same as &quot;confidential,&quot; &quot;not to be disclosed&quot; or with other clear indication of its status. If the information which Increment LTD. is disclosing is not in written form, for example, a machine or device, Increment LTD. shall be required prior to or at the same time that the disclosure is made to provide written notice of the secrecy claimed by Increment LTD.. {full_name} agrees upon reasonable notice to return the confidential tangible material provided by it by Increment LTD. upon reasonable request.</p><p>The obligation of non-disclosure shall terminate when if any of the following occurs:</p><p>(a) The confidential information becomes known to the public without the fault of {full_name}, or;</p><p>(b) The information is disclosed publicly by Increment LTD., or ;</p><p>(c) a period of months passes from the disclosure, or;</p><p>(d) the information loses its status as confidential through no fault of {full_name}.</p><p>In any event, the obligation of non-disclosure shall not apply to information which was known to {full_name} prior to the execution of this agreement.</p><p>Jul 27, 2015</p><p>Increment LTD.</p><p>{full_name}</p>');